language: java

jdk:
    - oraclejdk8

env:
    - TERM=dumb

before_script:
    - "./gradlew wrapper"

script:
    - "./gradlew check -i"

after_success:
    - "./gradlew jacocoTestReport coveralls"

branches:
  only:
    - master
    - ci
