language: java

jdk:
    - oraclejdk8

env:
    - TERM=dumb

script:
    - "./gradlew clean test -i"

after_success:
    - "./gradlew jacocoRootReport coveralls"

branches:
  only:
    - master
    - release
    - 1218-test-ci

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer